Variance fix
dafny-lang/dafny pull request #1240
Opened 2021-06-01 20:38 UTC by typerSniper

Type parameters of `iset` and domain of `imap` are now checked with a `Covariant_Permissive` context. If a parameter specified to be strict is used in those positions then dafny will give an error. Concrete examples are written in `Variance.dfy`.

2021-06-01 21:42 UTC, robin-aws commented
The failing checks are broken on master too - this PR fixes them: https://github.com/dafny-lang/dafny/pull/1237

2021-06-02 16:40 UTC, RustanLeino requested changes
I have some minor formatting comments. Please address.
Thanks for adding the many new good new tests. Please also add the specific example from https://github.com/dafny-lang/dafny/issues/1219.

2021-06-02 16:40 UTC, RustanLeino commented on Source/Dafny/Resolver.cs
> +
This and L14187 below make me think your IDE is set to insert blank lines before `if` statements or blocks. If you didn't intentionally insert this line, please adjust your IDE style formatting settings.

2021-06-02 16:40 UTC, RustanLeino commented on Source/Dafny/Resolver.cs
> +          lax || !t.Finite);
Make this one line. (If the change was done by the IDE formatting, you can change the line width to something much larger. I think even 150 characters is reasonable with today's wide screens.)
Same comment on L14163.

2021-06-02 16:40 UTC, RustanLeino commented on Source/Dafny/Resolver.cs
> +      } else if(type is SetType){
```suggestion
      } else if (type is SetType) {
```

2021-06-08 17:53 UTC, RustanLeino approved these changes

2021-06-08 17:54 UTC, merged