Add missing ghost modifier when printing VarDeclStmt
dafny-lang/dafny pull request #1286
Opened 2021-07-12 15:22 UTC by keyboardDrummer

Fixes #1280

### Changes
- Add missing ghost modifier when printing VarDeclStmt
- Rename the property `IsAutoGhost` to `HasGhostModifier` and flip the boolean value. LMK if anyone has concerns.

### Testing 
I haven't added a test, because I didn't want to add a test to just test a small part of the printer. I think we should have a printing test with a bigger scope, for example one that prints a Dafny program from memory, parses it and then checks that it's still the same in-memory program.

I can add a test like that as part of this PR if others feel it's a good idea.

2021-07-12 17:20 UTC, RustanLeino commented
Nice changes!

Regarding testing, I suggest just adding one line to some test that currently uses `/dprint:-` or `/rprint:-`.

(A note about your more ambitious test suggestion: a small number of tests currently re-run Dafny on the `/dprint`'ed output: `LetExpr.dfy`, `SmallTests.dfy`, `Calculations.dfy`, `GhostPrint.dfy`, and `DirtyLoops.dfy`.)

2021-07-12 17:22 UTC, RustanLeino requested changes

2021-07-12 17:22 UTC, RustanLeino commented on Source/Dafny/DafnyMain.cs
> +        if (filename == null) return;
Please wrap curly braces around the then branch of the `if`.

2021-07-12 17:22 UTC, RustanLeino commented on Source/Dafny/DafnyAst.cs
> +    public bool HasGhostModifier;
Nice.

2021-07-13 12:48 UTC, keyboardDrummer commented
> Nice changes!
> 
> Regarding testing, I suggest just adding one line to some test that currently uses `/dprint:-` or `/rprint:-`.
> 
> (A note about your more ambitious test suggestion: a small number of tests currently re-run Dafny on the `/dprint`'ed output: `LetExpr.dfy`, `SmallTests.dfy`, `Calculations.dfy`, `GhostPrint.dfy`, and `DirtyLoops.dfy`.)

There's a test called PrettyPrinting which I added something to 😄

2021-07-13 15:05 UTC, RustanLeino approved these changes

2021-07-13 15:05 UTC, merged