ignore execution traces in lit
dafny-lang/dafny pull request #1308
Opened 2021-07-15 16:28 UTC by typerSniper

Ignore annoying anons

2021-07-16 19:55 UTC, robin-aws requested changes
As discussed offline, we're going to go with using the Boogie `/errorTrace:0` option instead.

2021-07-17 00:46 UTC, typerSniper commented
in the process of doing so.

2021-07-20 23:35 UTC, RustanLeino approved these changes

2021-07-20 23:48 UTC, robin-aws approved these changes

2021-07-21 21:43 UTC, merged