Print string as string, not as a seq of char
dafny-lang/dafny pull request #1393
Opened 2021-08-26 03:01 UTC by sorawee

Before this PR:

```
method Main() {
  print ["abc"], "\n";
  print [['a', 'b', 'c']], "\n";
  var x : seq<char>;
  print [x], "\n";
  print [seq(5, x => 'a')], "\n";
}
```

outputs as follows:

Java:

```
[[a, b, c]]
[[a, b, c]]
[[]]
[[a, a, a, a, a]]
```

C#:

```
[abc]
[abc]
[]
[aaaaa]
```

JS & Go:

```
[abc]
[abc]
[[]]
[[a, a, a, a, a]]
```

This PR fixes the discrepancies. After the PR:

Java & C# & Go & JS:

```
[abc]
[abc]
[]
[aaaaa]
```

2021-09-28 21:58 UTC, RustanLeino requested changes

2021-09-28 21:58 UTC, RustanLeino commented on Source/Dafny/Compilers/Compiler-go.cs
> +      var fromType = (UserDefinedType)rawFromType;
```suggestion
      var fromType = (ArrowType)expr.Initializer.Type.NormalizeExpand();
```

This is simpler and is how it's done for JavaScript below.

2021-09-28 21:58 UTC, RustanLeino commented on Source/Dafny/Compilers/Compiler-go.cs
> +      if (((ArrowType)rawFromType).Result.IsCharType) {
```suggestion
      if (fromType.Result.IsCharType) {
```

2022-01-14 18:55 UTC, rakamaric commented
@RustanLeino could this be merged now? It seems that you maybe fixed the comments you had.
This is a bit time sensitive since we are trying to write up this work. Thanks a lot!

2022-01-14 19:41 UTC, RustanLeino approved these changes

2022-01-14 20:08 UTC, merged