Add encoding of concurrent programs to the test suite
dafny-lang/dafny pull request #1436
Opened 2021-09-15 08:11 UTC by fpoli

I'm going to add more examples in the next few days.

2021-09-16 12:02 UTC, fpoli commented
One program, `Test/concurrency/12-MutexLifetime-long.dfy` takes about 17 minutes to verify. `Test/concurrency/12-MutexLifetime-long.dfy` version that verifies a subset of the former file in about 4 minutes. For both of them, the verification time can be halved by using more vcsCores.

2021-09-16 23:46 UTC, RustanLeino requested changes
Thanks for contributing these programs. They use many features that we haven't exercised much before (e.g., two-state predicates). The code looks nice and contains comments that can be understood by someone trying to replicate or automate the work.

* Please add a `README.md` file in the test folder that says a few words about these test files (namely, that they are hand-coded versions of what the proof obligations in an imagined _concurrent Dafny using the LCI methodology_ would look like).
* I prefer that we mark the 17-minute file as `UNSUPPORTED` (or whatever the `lit` keyword is to omit a test file). That way, we still have the example in the test folder, but we don't severely increase the overall time needed to run the test suite.
* Please make the following code formatting changes throughout:
    - Use 2 spaces (not 4) for the indentation level
    - Use a space between a declared identifier and its type (e.g., `o: O`) (this occurs only a few times in all the files)
    - Remove the semi-colon at the end of field declarations (`var` and `const`)

2021-09-17 15:15 UTC, RustanLeino approved these changes

2021-09-17 15:56 UTC, RustanLeino approved these changes

2021-09-17 16:15 UTC, merged