add dafny libraries as submodule
dafny-lang/dafny pull request #1446
Opened 2021-09-19 19:16 UTC by yizhou7

Following the [comment](https://github.com/dafny-lang/dafny/issues/1236#issuecomment-922506972) from @robin-aws , I am attempting to add the dafny library as a submodule located under `Test` directory.

2021-09-19 21:16 UTC, robin-aws commented
This is passing but isn't actually cloning the submodule. :) Looks like we need to add `submodules: true` to the relevant `checkout` action.

2021-09-19 21:17 UTC, robin-aws requested changes
This is passing but isn't actually cloning the submodule. :) Looks like we need to add `submodules: true` to the relevant `checkout` action.

2021-09-19 22:21 UTC, yizhou7 commented
> This is passing but isn't actually cloning the submodule. :) Looks like we need to add `submodules: true` to the relevant `checkout` action.

@robin-aws Sorry, I am not super familiar with git  submodule. Is it possible to do something like `git clone --recurse-submodules` in or `git submodule update --init --recursive` in the CI? Or are you suggesting some changes on this repository itself?

2021-09-20 18:36 UTC, robin-aws commented
No worries! You should just need to add `submodules: true` immediately below this line: https://github.com/dafny-lang/dafny/blob/master/.github/workflows/msbuild.yml#L114

2021-09-21 19:25 UTC, robin-aws commented
Aha, the `lit.site.cfg` in the `libraries` module is not exactly the same as the one in `dafny`, in that they define `%dafny` differently: the former is assuming `dafny` is on the PATH, but the latter is running the Dafny CLI from source using `dotnet` instead.

I'll have to put some thought into how to resolve that.

2021-09-24 17:47 UTC, robin-aws commented on .github/workflows/msbuild.yml
> +    - run: rm Test/libraries/lit.site.cfg
HA, cute. :)

```suggestion
    - run: rm dafny/Test/libraries/lit.site.cfg
```

(you just haven't changed into the `dafny` directory yet at this point)

Worth adding a comment here too as to why you have to do this.

2021-09-30 20:19 UTC, merged