Add option to mimic the verification behavior of Dafny 3.3
dafny-lang/dafny pull request #1687
Opened 2022-01-06 13:52 UTC by keyboardDrummer

### Changes

Add option to mimic the verification behavior of Dafny 3.3

### Testing

Manually checked that using this option on the CLI brings the verification behavior closer to Dafny 3.3

2022-01-06 16:33 UTC, cpitclaudel commented
Can we generalize this a bit, maybe `/compatibilityMode:3.3` and explain that the option is a best effort to mitigate changes between versions?  Right now it reads as if it's very specific to unstable proofs.

2022-01-06 17:16 UTC, keyboardDrummer commented
> Can we generalize this a bit, maybe `/compatibilityMode:3.3` and explain that the option is a best effort to mitigate changes between versions? Right now it reads as if it's very specific to unstable proofs.

I wasn't expecting this option to ever effect anything other than verification, hence the name. Verification in particular is something that is difficult to be fully backwards compatible for because of the nature of unstable proofs, but in other aspects I think we should either be backwards compatible (99% of the time) or otherwise I think we would ask customers to migrate.

2022-01-06 17:20 UTC, cpitclaudel commented
OK, your call :)

2022-01-07 01:52 UTC, RustanLeino requested changes

2022-01-07 01:52 UTC, RustanLeino commented on Source/Dafny/DafnyOptions.cs
> +    Accepted versions are: 3.3 (note that this turns of features that prevent classes of verification instability)
```suggestion
    Accepted versions are: 3.3 (note that this turns off features that prevent classes of verification instability)
```
```suggestion
    Accepted versions are: 3.3 (note that this turns of features that prevent classes of verification instability)
```

2022-01-10 18:08 UTC, RustanLeino approved these changes
This seems like a fine option for now, but I don't expect we'll support the `3.3` option indefinitely.

2022-01-11 01:41 UTC, merged