fix: "Stuck on Verifying..."
dafny-lang/dafny pull request #1771
Opened 2022-01-28 22:30 UTC by MikaelMayer

This PR adds no new code because the fix is in Boogie:
https://github.com/boogie-org/boogie/pull/491

However, it does add a test that is currently failing, which will be fixed once the Boogie PR above is merged and.
This tests asks the verifier to do something hard, and cancels verification by performing a change on the text.
Currently, the verifier is stuck verifying, but with the fix above, it will cancel verification, kill zombie processes, and continue smoothly

2022-02-22 22:06 UTC, keyboardDrummer approved these changes

2022-02-23 18:19 UTC, camrein requested changes
Only some small inputs, and it appears something's wrong with the tests.
I'm quite impressed that this feature didn't require changes to the language server itself. 😄
This will sure have a huge impact on UX.

2022-02-23 18:19 UTC, camrein commented on Source/DafnyLanguageServer.Test/Various/CancelVerification.cs
> +      Thread.Sleep(5000);
Prefer using `await Task.Delay(5_000);` here

2022-02-28 11:01 UTC, camrein commented
Just in case you're waiting for the approval: I think you didn't push your latest changes. 😄

2022-02-28 16:07 UTC, MikaelMayer commented
Indeed, I did not, because there is still a problem in Boogie where counter-examples are not reported correctly anymore. I'll be waiting on Boogie to be compatible with Dafny again to solve this issue.

2022-03-01 18:20 UTC, MikaelMayer commented on Source/DafnyLanguageServer/Language/DafnyProgramVerifier.cs
> +      using (cancellationToken.Register(() => CancelVerification(requestId))) {
```suggestion
      using (cancellationToken.Register(() => CancelVerification(uniqueRequestId))) {
```

2022-03-04 15:02 UTC, camrein approved these changes

2022-03-04 15:24 UTC, merged