chore: Added favicon to Dafny documentation
dafny-lang/dafny pull request #1867
Opened 2022-02-28 16:40 UTC by MikaelMayer

I added a favicon with the current Dafny logo. It will make it easier to find the Dafny reference among the tabs.
Fixes #1107

Originally, I was putting the original logo, but it's creepy as it's too small.
![image](https://user-images.githubusercontent.com/3601079/156018554-e00ffeee-abc7-4622-b23b-211c8c3683c7.png)
It's better than nothing, but I think we should think of 
Thus I extracted the first letter, and this is the new favicon:
![image](https://github.com/dafny-lang/dafny/raw/f49de8d3dea81f82b9440b9d9224d813c9a71b61/docs/_site/assets/dafny-favicon.png)
I have no idea if this PR works as intended. I tried to install Ruby, Bundler and Jekyll, but the commands to run the server don't work for me.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

2022-02-28 17:17 UTC, cpitclaudel requested changes

2022-02-28 17:17 UTC, cpitclaudel commented on docs/_includes/head.html
> +  <link rel="icon" type="image/x-icon" href="../assets/dafny-favicon.png">
Type should be `type="image/png"`; `x-icon` is for ICO files I think

2022-03-02 16:39 UTC, cpitclaudel approved these changes
Lovely :)

2022-03-02 21:50 UTC, merged

2022-03-03 09:39 UTC, mschlaipfer commented
Neat! 💯 I don't see it yet, though.