feat: `class`es and `newtype`s
dafny-lang/dafny pull request #1891
Opened 2022-03-09 15:23 UTC by fabiomadge

Add two new constructs.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

2022-03-09 16:45 UTC, MikaelMayer requested changes
Just a few minor things, great job moving the python compiler forward and adding a new step to elaborate another compiler

2022-03-09 16:45 UTC, MikaelMayer commented on Source/Dafny/Compilers/Compiler-python.cs
> +      return new ClassWriter(this, constructorWriter: constructorWriter, methodWriter: methodWriter);
Can't you just put the methodWriter first and the constructorWriter second, so that you don't need to duplicate parameter names?

2022-03-16 16:04 UTC, MikaelMayer commented on Source/Dafny/Compilers/Compiler-python.cs
> +      d = TypeInitializationValue(udt, wr, nt.tok, false, false);
```suggestion
      var d = TypeInitializationValue(udt, wr, nt.tok, false, false);
```

2022-03-16 16:04 UTC, MikaelMayer commented on Source/Dafny/Compilers/Compiler-python.cs
> +      string d;
```suggestion
```

2022-03-16 17:27 UTC, fabiomadge commented
Thanks!

2022-03-16 21:07 UTC, MikaelMayer approved these changes
Great to see classes supported with constructors! Thank you!

2022-03-16 22:39 UTC, merged

2022-03-24 18:44 UTC, fabiomadge commented
```Python
# Dafny program 4_Calls-FunctionsValues-Class+NT.dfy compiled into Python
from typing import Callable

class _dafny:
  def print(value):
    if type(value) == bool:
      print("true" if value else "false", end="")
    elif type(value) == property:
      print(value.fget(), end="")
    else:
      print(value, end="")

class _System:
  class nat:
    def Default():
      return int(0)

class FunctionValues_Compile:
  class Class:
    def  __init__(self):
      self._x: int = int(0)

    def _ctor(self, x):
      self._x = x

    def F(self):
      return (self).x

    @staticmethod
    def G():
      return 3

    @property
    def x(self):
      return self._x

  class NT:
    def Default():
      return int(0)

    @staticmethod
    def F(self):
      return self

    @staticmethod
    def G():
      return 3


  class _default:
    @staticmethod
    def Test():
      _25_c: FunctionValues_Compile.Class
      _nw0 = FunctionValues_Compile.Class()
      _nw0._ctor(5)
      _25_c = _nw0
      _26_nt: FunctionValues_Compile.NT
      _26_nt = 5
      FunctionValues_Compile._default.ApplyAndPrint(_25_c.F)
      FunctionValues_Compile._default.ApplyAndPrint(FunctionValues_Compile.Class.G)
      FunctionValues_Compile._default.ApplyAndPrint((lambda _eta_this0: lambda: FunctionValues_Compile.NT.F(_eta_this0))(_26_nt))
      FunctionValues_Compile._default.ApplyAndPrint(FunctionValues_Compile.NT.G)
      _dafny.print("\n")
      _27_x0: Callable
      _28_x1: Callable
      _29_x4: Callable
      _30_x5: Callable
      _rhs0: Callable = _25_c.F
      _rhs1: Callable = FunctionValues_Compile.Class.G
      _rhs2: Callable = (lambda _eta_this1: lambda: FunctionValues_Compile.NT.F(_eta_this1))(_26_nt)
      _rhs3: Callable = FunctionValues_Compile.NT.G
      _27_x0 = _rhs0
      _28_x1 = _rhs1
      _29_x4 = _rhs2
      _30_x5 = _rhs3
      _nw1 = FunctionValues_Compile.Class()
      _nw1._ctor(2)
      _25_c = _nw1
      _26_nt = 2
      _dafny.print(_27_x0())
      _dafny.print(" ")
      _dafny.print(_28_x1())
      _dafny.print(" ")
      _dafny.print(_29_x4())
      _dafny.print(" ")
      _dafny.print(_30_x5())
      _dafny.print("\n")

    @staticmethod
    def ApplyAndPrint(f):
      _dafny.print(f())
      _dafny.print(" ")


class _module:
  class _default:
    @staticmethod
    def Main():
      FunctionValues_Compile._default.Test()


_module._default.Main()
```