Properly check if types may contain references
dafny-lang/dafny pull request #1924
Opened 2022-03-21 22:49 UTC by RustanLeino

Previously, types were not properly checked for whether or not they may contain references. This PR fixes that.

Fixes #1419

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

2022-03-22 05:39 UTC, cpitclaudel approved these changes
For datatypes, why is it enough to check just the type parameters?  The following looks off to me:

```
class C {}
datatype D = DC(c: C)
type X(!new) = D // No error

datatype Obs' = Obs'(s: set<object>)
predicate lotsOfObjects'() {
  exists o: Obs' :: |o.s| > 10 // No error
}
```

And also this:

```
class C {}

datatype Box<T> = Box(t: T)
type Box'(!new) = Box<C> // Rejected

datatype BoxC = BoxC(c: C)
type BoxC'(!new) = BoxC // No error
```

Am I missing something?

2022-03-22 19:40 UTC, RustanLeino commented
@cpitclaudel Thank you. These are (still) bugs.

2022-03-24 15:46 UTC, RustanLeino commented
@cpitclaudel I addressed the further issues in this PR with the commit I just pushed. However, the fix causes errors that the old Schorr-Waite test programs have a function that depends on the allocation state. To sort this out, Dafny needs a more flexible mechanism to indicate that quantifiers only quantify over allocated state. I will add this mechanism in a separate PR and then return to this one.

2022-03-28 17:29 UTC, cpitclaudel requested changes

2022-03-28 17:29 UTC, cpitclaudel commented on Source/Dafny/AST/DafnyAst.cs
> +      return false;
Is false the right default here?  It risks blowing up silently if we add more AST nodes later.

2022-03-30 19:17 UTC, cpitclaudel approved these changes
Very nice, thanks!

2022-04-28 17:41 UTC, cpitclaudel approved these changes

2022-04-28 18:38 UTC, merged