Use a large stack scheduler in DafnyDriver
dafny-lang/dafny pull request #2125
Opened 2022-05-10 09:34 UTC by keyboardDrummer

Fixes 2042

### Testing

On my machine this makes the test `git-issue-267.dfy` pass again, both in the DEBUG and RELEASE configuration. However, on the build it was already passing so no change there :/

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

2022-05-10 10:33 UTC, fabiomadge requested changes
Thanks for fixing this!

2022-05-10 10:33 UTC, fabiomadge commented on Source/DafnyDriver/DafnyDriver.cs
> +using Microsoft.Dafny.LanguageServer.Workspace;
Maybe we should moves this to a more neutral place, if using the simple threading API really doesn't suffice.

2022-05-10 10:33 UTC, fabiomadge commented on Source/DafnyDriver/DafnyDriver.cs
>        return ret;
Shouldn't we set this to something?

2022-05-10 10:41 UTC, keyboardDrummer commented on Source/DafnyDriver/DafnyDriver.cs
>        return ret;
Good catch 😅

2022-05-10 12:37 UTC, fabiomadge approved these changes

2022-07-22 20:28 UTC, cpitclaudel commented
Why did we never merge this?

2022-07-26 08:28 UTC, keyboardDrummer commented
> Why did we never merge this?

Because it means Dafny may spawn multiple large threads, making it consume even more memory that is likely not used. It would be safer though. I would be OK with merging this, just saying there's also a downside to doing so.

2022-08-02 13:11 UTC, closed without merging