fix: Redirect Console.Write to the logger in LSP
dafny-lang/dafny pull request #2144
Opened 2022-05-16 23:19 UTC by MikaelMayer

This PR immediately redirects all further calls to `Console.Write` to the logger, so that the language server won't crash anymore just because some code uses `Console.Write`.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

2022-05-17 10:32 UTC, camrein requested changes
That's exciting!

2022-05-17 10:32 UTC, camrein commented on Source/DafnyLanguageServer/Program.cs
>          await server.WaitForExit;
The `TextWriter` is disposable, so make sure all resources are freed.
```suggestion
        // Prevent any other parts of the language server to actually write to standard output.
        await using var logWriter = new LogWriter();
        Console.SetOut(logWriter);
        shutdownServer = () => server.ForcefulShutdown();
        await server.WaitForExit;
```

2022-05-17 10:32 UTC, camrein commented on Source/DafnyLanguageServer/Program.cs
> +  internal class LogWriter : TextWriter {
Since `LogWriter` is only used by the `Program` type, I suggest making it an inner `private` class.

2022-05-17 10:32 UTC, camrein commented on Source/DafnyLanguageServer/Program.cs
> +    }
Two suggestions:
- Use `Log.Logger` with the suitable method for the desired log-level.
- Always use a format string to not accidentally provide format-patterns to the logging framework which can cause errors (or even worse). Furthermore, it makes it easier to scan the logs for this kind of log messages.


```suggestion
    public override void Write(char value) {
      Log.Logger.Verbose("unexpected console output: {value}", value);
    }

    public override void Write(string? value) {
      Log.Logger.Verbose("unexpected console output: {value}", value);
    }
```

PS: You may want to test my suggestions, I'm not entirely sure that I got it right.

2022-05-17 16:00 UTC, MikaelMayer commented
The code portion I wrote on `Program.cs` is XUnit-untested because all the tests rely on a custom creation of the language server, which would not suffer the shortcoming because it's defining its own pipes.

However, I did used the compiled PluginsTest.cs as a plugin for VSCode to actually write to Console.Out during resolution. Without this PR, it fails silently (no error message). With this PR, it succeeds.

Hence, I now switch this PR state to "ready for review" because I wouldn't know how to test it further, unless you have some advice.

2022-05-18 12:48 UTC, camrein approved these changes
Fantastic! Let's hope this resolves the issue, but I'm positive that your intuition for the root-cause is right.

2022-05-18 15:27 UTC, merged

2022-05-18 15:51 UTC, keyboardDrummer commented
Nice!