Release guide update for VSCode plugin
dafny-lang/dafny pull request #2165
Opened 2022-05-25 20:53 UTC by prvshah51

Adding information about updating and releasing new version of ide-vscode to provide new version of Dafny to VSCode plugin users.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

2022-05-25 21:17 UTC, atomb requested changes
The content looks good. I just suggested a few grammatical improvements.

2022-05-25 21:17 UTC, atomb commented on RELEASE.md
> +1. Build the Ide-vscode locally from https://github.com/dafny-lang/ide-vscode .
```suggestion
1. Build ide-vscode locally from https://github.com/dafny-lang/ide-vscode .
```

2022-05-25 21:17 UTC, atomb commented on RELEASE.md
> +3. add the new Dafny version number under `dafny.preferredVersion` list in file `package.json`  .
```suggestion
3. Add the new Dafny version number to the `dafny.preferredVersion` list in the `package.json` file.
```

2022-05-25 21:17 UTC, atomb commented on RELEASE.md
> +4. Update the value of constant `LatestVersion` In the file `src/constants.ts` to new version number (.
```suggestion
4. Update the value of the constant `LatestVersion` in the file `src/constants.ts` to the new version number.
```

2022-05-25 21:17 UTC, atomb commented on RELEASE.md
> +5. Before releasing a new version of the VSCode plugin, Make sure to add the Release notes  in file `CHANGELOG.md`
```suggestion
5. Before releasing a new version of the VSCode plugin, make sure to add to the release notes in `CHANGELOG.md`
```

2022-05-25 21:17 UTC, atomb commented on RELEASE.md
> +6. Select a new version number $VER for Plugin(e.g. "2.4.0") and change the value of the constant `version` in the file `package,json`
```suggestion
6. Select a new version number `$VER` for the plugin (e.g. "2.4.0") and change the value of the constant `version` in the file `package.json`
```

2022-05-25 21:17 UTC, atomb commented on RELEASE.md
> +   to $VER and commit the changes.
```suggestion
   to `$VER` and commit the changes.
```

2022-05-25 21:17 UTC, atomb commented on RELEASE.md
> +8. Create a pull request and once merged ,A GitHub action will automatically run in reaction to the tag being pushed to master, which will create a new release in the VSCode marketplace.
```suggestion
8. Create a pull request and, once merged, a GitHub action will automatically run in reaction to the tag being pushed to master, which will create a new release in the VSCode marketplace.
```

2022-05-25 23:35 UTC, atomb approved these changes
Looks good!

2022-05-25 23:36 UTC, merged

2022-05-27 18:24 UTC, MikaelMayer commented
Fantastic ! Thanks for taking care of documenting this process.