trying out new java version
dafny-lang/dafny pull request #2297
Opened 2022-06-24 13:54 UTC by prvshah51

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

2022-06-28 10:17 UTC, keyboardDrummer approved these changes

2022-06-29 10:18 UTC, keyboardDrummer approved these changes

2022-06-29 18:53 UTC, robin-aws requested changes
Glad things still work on a much newer JDK, but no longer running on 1.8 means we might accidentally start emitting Java code that requires a newer Java version and break users.

We can ADD building on Java 18 if we want assurance that we support that too, however. I'd suggest another dimension on the `integration-tests-reusable.yml` workflow, something like `target-language-version: ["oldest", "newest"]`. We can have each target language define their oldest supported version independently. We'll probably want to only run with "newest" in the nightly build mind you.

2022-07-28 22:01 UTC, robin-aws commented on .github/workflows/integration-tests-reusable.yml
> +      if: matrix.target-language-version == "oldest"
Turns out double quotes are a syntax error (https://github.com/dafny-lang/dafny/actions/runs/2756979457) - string literals have to use single quotes: https://docs.github.com/en/actions/learn-github-actions/expressions#literals

2022-08-05 16:18 UTC, robin-aws approved these changes
Thanks! It'll be great to hook up `oldest` for the other languages in the near future too.

2022-08-05 18:31 UTC, merged