fix: Issue #2415
dafny-lang/dafny pull request #2419
Opened 2022-07-15 01:27 UTC by davidcok

Fixes #2415

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

2022-07-15 19:33 UTC, MikaelMayer requested changes
Thanks. I did not know about the lambda initialization for arrays. Very useful.

2022-07-15 19:33 UTC, MikaelMayer commented on docs/DafnyRef/Types.md
> +member.  For example, the array allocated with `a := new int[5];` satisfies:
```suggestion
member.  For example, the array allocated with `a := new T[n];` satisfies:
```

2022-07-15 19:40 UTC, robin-aws requested changes

2022-07-15 19:44 UTC, MikaelMayer approved these changes
you might want to consider @robin-aws 's suggestion as well.

2022-07-15 19:45 UTC, davidcok commented
Yes - I added some txt for that also.

> On Jul 15, 2022, at 3:44 PM, Mikaël Mayer ***@***.***> wrote:
> 
> 
> @MikaelMayer approved this pull request.
> 
> you might want to consider @robin-aws <https://github.com/robin-aws> 's suggestion as well.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/dafny-lang/dafny/pull/2419#pullrequestreview-1040738920>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ABITDQEJKR4DKTVXIE2JN63VUG5SJANCNFSM53UBP2IA>.
> You are receiving this because you authored the thread.
>

2022-07-15 19:46 UTC, MikaelMayer approved these changes

2022-07-15 19:51 UTC, robin-aws approved these changes

2022-07-15 22:26 UTC, merged

2022-07-15 22:39 UTC, cpitclaudel commented
I believe this was already documented here:

`````
## 21.16. Array Allocation
````grammar
ArrayAllocation_ =
  "new" [ Type ] "[" [ Expressions ] "]"
  [ "(" Expression(allowLemma: true, allowLambda: true) ")"
  | "[" [ Expressions ] "]"
  ]
````

This allocates a new single or multi-dimensional array as explained in
section [Section 15](#sec-array-types).
The initialization portion is optional. One form is an
explicit list of values, in which case the dimension is optional:
```dafny
var a := new int[5];
var b := new int[5][2,3,5,7,11];
var c := new int[][2,3,5,7,11];
var d := new int[3][4,5,6,7]; // error
```
The comprehension form requires a dimension and uses a function of
type `nat -> T` where `T` is the array element type:
```dafny
var a := new int[5](i => i*i);
```
`````

2022-07-18 17:13 UTC, MikaelMayer commented
6 sections later ! We should probably add a link between these sections.