Add test logging
dafny-lang/dafny pull request #2579
Opened 2022-08-11 15:11 UTC by keyboardDrummer

Add more logging for:
- OpeningDocumentWithMultipleVerificationCoresReturnsStableDiagnostics
- Tests in ReorderingVerificationGutterStatusTester

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

2022-08-11 15:30 UTC, robin-aws requested changes

2022-08-11 15:30 UTC, robin-aws commented on Source/DafnyLanguageServer.Test/GutterStatus/ReorderingVerificationGutterStatusTester.cs
> +        }
Shouldn't there be a `throw;`?

2022-08-11 16:16 UTC, robin-aws approved these changes

2022-08-16 17:09 UTC, cpitclaudel approved these changes

2022-08-16 17:09 UTC, merged