Fixing internal anchor syntax
dafny-lang/dafny pull request #2916
Opened 2022-10-22 17:52 UTC by davidcok

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

2022-10-23 22:10 UTC, cpitclaudel requested changes

2022-10-23 22:10 UTC, cpitclaudel commented on docs/DafnyRef/UserGuide.md
> +<a id="sec-function-syntax"/>
I think you need a newline after this to go back to markdown (otherwise the whole paragraph below is HTML)

2022-10-24 17:42 UTC, davidcok commented
I added the blank line (and fixed another bad line break). But despite that being the rule for many HTML blocks, the text after the HTML anchor did not render any differently -- so perhaps the blank line is not needed for anchor tags. The bank line does not hurt though.

2022-10-25 03:35 UTC, davidcok commented on docs/DafnyRef/UserGuide.md
> +    `-functionSyntax:4`. This will
To keep markdown from line breaking between the `-` and `functionSyntax:4`

2022-10-28 16:47 UTC, cpitclaudel approved these changes

2022-10-28 16:47 UTC, merged