Update ISSUE_TEMPLATE.md
dafny-lang/dafny pull request #2965
Opened 2022-11-01 18:21 UTC by MikaelMayer

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

2022-11-01 18:26 UTC, cpitclaudel requested changes
I think that's not right: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates says ISSUE_TEMPLATE should be a directory.

2022-11-01 20:20 UTC, cpitclaudel requested changes
Looks  great!  Should we add another template for our own tasks (since we use the repo a lot for that), and maybe a freeform option as well?

2022-11-01 20:20 UTC, cpitclaudel commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - 3.7.X
How about making this freeform, so we don't have to keep updating it?

2022-11-01 20:20 UTC, cpitclaudel commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +      label: What version of Dafny were you using?
Maybe we could explain how to find out the version

2022-11-01 20:20 UTC, cpitclaudel commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        If you are having trouble with a proof?  Consider posting your question on [Stack Overflow](https://stackoverflow.com/questions/ask?tags=dafny).
```suggestion
        Are you having trouble with a proof?  Consider posting your question on [Stack Overflow](https://stackoverflow.com/questions/ask?tags=dafny).	  
```

2022-11-01 20:20 UTC, cpitclaudel commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +labels: []
`kind: bug` here?

2022-11-01 20:20 UTC, cpitclaudel commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +      label: Code to produce this issue.
No periods here I think (these are titles IIRC)

2022-11-01 20:20 UTC, cpitclaudel commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +      description: "Please paste here what you ran and what were your your logs that you think ought to be different:"
What's a log?

2022-11-01 20:20 UTC, cpitclaudel commented on .github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml
> +        Thanks for taking the time to give us ideas on how to evolve the Dafny language!
It's not just that, thought, right?

2022-11-01 21:33 UTC, MikaelMayer commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +labels: []
```suggestion
labels: []
kind: bug
```

2022-11-01 21:42 UTC, MikaelMayer commented
> Looks great! Should we add another template for our own tasks (since we use the repo a lot for that), and maybe a freeform option as well?

I think there is always a freeform option available, so we could use it for our own tasks for now. Let's do this iteratively.

2022-11-01 21:43 UTC, MikaelMayer commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +labels: []
kind is not accepted

2022-11-02 19:55 UTC, fabiomadge commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +
```suggestion

```

2022-11-02 19:55 UTC, fabiomadge commented on .github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml
> +
```suggestion

```

2022-11-02 20:47 UTC, cpitclaudel commented on .github/ISSUE_TEMPLATE/BUG_REPORT.yml
> +        - Linux
Maybe we want to add an option for WSL?

2022-11-02 20:48 UTC, cpitclaudel submitted a review, later dismissed

2022-11-02 21:38 UTC, cpitclaudel approved these changes
👏

2022-11-03 04:32 UTC, merged