Issue 2676: Fix typos and remove .edit, .editonly annotations
dafny-lang/dafny pull request #3135
Opened 2022-11-29 22:05 UTC by davidcok

Fixes #2676

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

2022-11-29 23:00 UTC, atomb requested changes
This looks great. I noticed one typo and have a couple of small questions.

2022-11-30 00:17 UTC, davidcok commented on docs/OnlineTutorial/Sequences.md
> +the first and last elements, and getting everything but the first cworand last
Aah - vi is often quicker for me, but I do get out of synch with the editing mode...

2022-11-30 00:18 UTC, davidcok commented on docs/OnlineTutorial/guide.md
> +  ... ...
Should have been removed...

2022-11-30 00:20 UTC, davidcok commented on docs/OnlineTutorial/guide.md
> -argument. (See the tutorial on memory for more on allocation.)
Correct.

2022-11-30 00:37 UTC, atomb approved these changes
Looks good!

2022-11-30 20:07 UTC, merged