Pre-Dafny 4 edits to Expressions chapter
dafny-lang/dafny pull request #3533
Opened 2023-02-14 14:54 UTC by davidcok

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

2023-02-14 22:43 UTC, alex-chew requested changes

2023-02-14 22:46 UTC, davidcok commented on docs/DafnyRef/Expressions.md
>  var a := 2*b; a*b
Correct. Changed.

2023-02-14 22:54 UTC, alex-chew requested changes

2023-02-14 22:54 UTC, alex-chew commented on docs/DafnyRef/Expressions.md
> +Note that `multiset{1, 1})` is a multiset holding the value `1` with multiplicity 2,
```suggestion
Note that `multiset{1, 1}` is a multiset holding the value `1` with multiplicity 2,
```

2023-02-15 00:11 UTC, alex-chew approved these changes

2023-02-15 04:58 UTC, merged