fix: (Test Generation) Better Error Messages and Variable Names
dafny-lang/dafny pull request #3711
Opened 2023-03-08 04:08 UTC by Dargones

Fixes #3708 

This PR improves test generation based on recent feedback by adding clearer error messages and variable names that are based on the given variable's type. Full changelog:

- Terminate test generation with a dedicated error if no test methods are generated.
- Terminate test generation with a dedicated error if the target method cannot be found (previously the program would crush).
- Improve explanation of cases in which a test is not generated due to verification being successfull or timing out.
- Name generated variables in accordance with their type (e.g. int0 and bool0 as opposed to v0 and v1).
- Fix several typos.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

2023-03-08 17:00 UTC, atomb requested changes
This is a nice improvement! There will need to be some changes to resolve conflicts with a recent PR, though.

2023-03-09 01:30 UTC, Dargones commented on Source/DafnyTestGeneration/ProgramModification.cs
> +            "because the verifier succeeded. This can be caused by dead code.");
This makes sense - paraphrased this to "because the verifier proved that no inputs could cause this block to be visited"

2023-03-09 01:30 UTC, Dargones commented on Source/DafnyTestGeneration/Main.cs
> +      if (DafnyOptions.O.TestGenOptions.TargetMethod != null) {
Done!

2023-03-09 01:32 UTC, Dargones commented
Thank you, @atomb. I noticed that the recent changes with DafnyOptions broke a few things, so I added minor fixes for these to this PR as well (two of the last three items on the list of changes above).

2023-03-10 07:00 UTC, Dargones commented
Made a small change (commit above) to align this PR with the one I am preparing next but otherwise everything should be the same.

2023-03-23 00:06 UTC, atomb approved these changes

2023-03-23 00:37 UTC, merged