Documentation on docstrings
dafny-lang/dafny pull request #3773
Opened 2023-03-21 14:57 UTC by davidcok

Accompanies PR 3756

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

2023-03-21 15:52 UTC, MikaelMayer requested changes
Tiny changes

2023-03-21 15:52 UTC, MikaelMayer commented on docs/DafnyRef/Grammar.md
> +      documentation string
```suggestion
* The extraction of the doc-string from a multiline comment follow these rules 
  * On the first line, an optional `*` right after `/*`and an optional space are removed, if present
  * On other lines, the indentation space (with possibly one star in it) is removed, as if the content was supposed to align with A if the comment started with `/** A` for example.
```

2023-03-21 15:59 UTC, davidcok commented on docs/DafnyRef/Grammar.md
> +* Documentation comments are recommended to begin with `/**`, though some
Rephrased

2023-03-21 16:00 UTC, davidcok commented on docs/DafnyRef/Grammar.md
> +* Doc-comments after the declaration are preferred.
OK

2023-04-06 18:41 UTC, MikaelMayer approved these changes

2023-04-06 22:52 UTC, merged