[Test Generation] Increase stack size during translation
dafny-lang/dafny pull request #3897
Opened 2023-04-22 00:35 UTC by Dargones

Since test generation can now be done asynchronously, stack overflow is possible on large files due to the way the translator works. This PR makes sure the translator is called from a special thread that has enough stack space allocated for it.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

2023-04-27 00:10 UTC, atomb requested changes

2023-04-27 00:10 UTC, atomb commented on Source/DafnyTestGeneration/Utils.cs
> +    .Translate(program, program.Reporter)
This is a tiny nit, but could indent this line and the following beyond the indentation level of `ret`?

2023-04-27 19:19 UTC, Dargones commented on Source/DafnyTestGeneration/Utils.cs
> +    .Translate(program, program.Reporter)
Done!

2023-04-27 23:31 UTC, atomb approved these changes
Looks good!

2023-05-01 14:54 UTC, keyboardDrummer approved these changes

2023-05-01 15:54 UTC, merged