Disable ShowSnippets during Test Generation
dafny-lang/dafny pull request #4216
Opened 2023-06-25 01:40 UTC by Dargones

The `--show-snippets` breaks test generation because it relies on casting of `Boogie.IToken` to `Dafny.IToken` [here](https://github.com/dafny-lang/dafny/blob/d72dc7a85ae5d662dda78f927463d1e56b4a0696/Source/DafnyCore/DafnyConsolePrinter.cs#L54) and test generation makes changes to the Boogie AST that may introduce new tokens that cannot be cast. This PR disables the option, recently enabled by default, during test generation. An alternative would be to surround the cast with try-catch, but it seems that outside test generation purposes it is probably safe to assume that the cast succeeds. @atomb, @robin-aws would it be possible to merge this before the next release to make sure test generation stays stable? 

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

2023-06-25 01:57 UTC, davidcok reviewed
I suggest you add a comment in the ref-man as well that --show-snippets is always disabled for these two commands.

2023-06-25 02:29 UTC, Dargones commented
Thank you for pointing out to the reference manual, @davidcok! I have added a note about `--show-snippets` and have fixed a few things in the existing description of the `generate-tests` option as well.

2023-06-26 16:08 UTC, Dargones commented
> Can't we change that?

In principle, yes, and I am working on an overhaul of inlining that will move many AST traversals from Boogie to Dafny and move the code closer to addressing this issue. However, I don't think I know of a way to immediately make sure all tokens can be cast. One major obstacle is that I need to copy Boogie ASTs and the only way of doing this is by printing them to file and then parsing, which loses all connection to Dafny tokens.

In the near future, I think, the only way of making sure test generation does not break is by disabling `--sow-snippets`.

2023-06-26 22:03 UTC, atomb requested changes
This mostly looks great. The one suggestion I have is to also fix ShowSnippets for the case where there is no Dafny source location information available. I'm thinking that you could replace this code:

https://github.com/dafny-lang/dafny/blob/d72dc7a85ae5d662dda78f927463d1e56b4a0696/Source/DafnyCore/DafnyConsolePrinter.cs#L104-L106

with something like

```dafny
    if (Options.Get(ShowSnippets)) {
      if(tok is IToken dafnyTok) {
        WriteSourceCodeSnippet(dafnyTok, tw);
      } else {
        ErrorWriteLine(tw, "No Dafny location information, so snippet can't be generated."); 
      }
    }
```

And then make `WriteSourceCodeSnippet` take a Dafny token instead of a Boogie token.

2023-06-27 04:32 UTC, Dargones commented
Thank you, @atomb! This makes sense, I have made the change.

2023-06-27 15:56 UTC, atomb commented
One tiny additional thing: it seems like the format check wants some white space changes.

2023-06-27 22:38 UTC, atomb approved these changes
Looks good!

2023-06-27 22:39 UTC, merged