Show method trying to verify as queued
dafny-lang/dafny pull request #4479
Opened 2023-08-25 12:48 UTC by keyboardDrummer

### Changes
- Methods that have been triggered to verify are shown as queued. In particular, methods that are still translating to Boogie or resolving Boogie are shown as queued. The IDE will be updated to show "preparing verification" when no symbols are running and some are queued.
- Return calls to `VerifySymbol` immediately, in particular before translating to Boogie

The above two changes make verification feel more responsive. There is no longer a dead period during which preparation of verification is done.

### Testing
Added test `TryingToVerifyShowsUpAsQueued`

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

2023-08-28 13:29 UTC, keyboardDrummer commented on Source/DafnyCore/Generic/Node.cs
> +      // If we parse a resolved document, some children sometimes have the same token because they are auto-generated
This is just a refactoring to prevent exception in happy-flow scenarios

2023-08-30 00:26 UTC, atomb requested changes
I saw two tiny things to change.

2023-08-30 00:26 UTC, atomb commented on Source/DafnyLanguageServer.Test/Util/Stringify.cs
> +  public static void Stringify(this object root, TextWriter writer, bool showNullChildren = false, IReadOnlyDictionary<System.Type, Action<object, TextWriter>> overrides = null) {
Nullable checks are enabled in this file, so there's a warning about `overrides` not being nullable.

2023-08-30 00:26 UTC, atomb commented on Source/DafnyLanguageServer/Workspace/SingleAddConcurrentDictionary.cs
> +public class LazyConcurrentDictionary<TKey, TValue> : IEnumerable<KeyValuePair<TKey, TValue>>
I'd make the name of this file match the class name.

2023-08-30 15:36 UTC, atomb approved these changes
Looks great!

2023-08-30 15:36 UTC, merged

2023-08-31 09:32 UTC, keyboardDrummer commented on Source/DafnyLanguageServer.Test/DafnyLanguageServerTestBase.cs
> +lemma {:timeLimit 1} SquareRoot2NotRational(p: nat, q: nat)
O yeah, good idea!