Add test for prover log regression
dafny-lang/dafny pull request #4558
Opened 2023-09-15 12:45 UTC by keyboardDrummer

### Changes

Add a test that notifies us when we make changes that change anything about verification, with the caveat that the Dafny input program is not using many Dafny features, so verification changes in specific Dafny features might be missed.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

2023-09-15 17:23 UTC, atomb approved these changes
Thanks for doing this! I left one comment, but it's not critical.

2023-09-15 17:23 UTC, atomb commented on Source/DafnyPipeline.Test/DafnyPipeline.Test.csproj
> +    <None Update="expectedProverLog.txt">
It's a tiny thing, but I might call this `expectedProverLog.smt2` or `SomeProgram.smt2`.

2023-09-15 22:06 UTC, robin-aws requested changes
VERY glad to have this, thanks. Blocking on deeply commenting the purpose here though - otherwise I worry some future contributor will update it blindly or even delete it, thinking it's just a poorly-written brittle unit test.

2023-09-15 22:06 UTC, robin-aws commented on Source/DafnyPipeline.Test/ProverLogStability.cs
> +    public async Task ProverLogRegression() {
I think we need a sizable comment here to describe the purpose of the test. Something like "this test only provides data on when changes are made that change the encoding of Dafny programs to SMT programs. A failure is meant to provide this data, not block changes - if you are contributing a change that makes it fail...". Probably even with some background about the fundamental brittleness problem.

2023-09-15 22:06 UTC, robin-aws commented on Source/DafnyPipeline.Test/ProverLogStability.cs
> +    readonly string originalProgram = @"
This is a good start at least, but I feel like it's likely one of the integration test files would cover more features, especially some non-trivial assertion verification.

2023-09-20 15:08 UTC, robin-aws approved these changes
Thanks for adding the comment :)

2023-09-20 21:01 UTC, robin-aws approved these changes
🚀

2023-09-20 21:43 UTC, merged