Fix: Ability to cast a datatype to its trait when overriding functions
dafny-lang/dafny pull request #4824
Opened 2023-11-28 18:23 UTC by MikaelMayer

This PR fixes #4823
There were two issues there:
- The function override check was casting to ClassLikeDecl, when it should now be TopLevelDeclWithMembers as IndDatatypeDecl can also override trait declarations.
- The generated axiom used to rely on types being unboxed, but since now we might compare a trait with a datatype value, we need to ensure correct boxing for Boogie to type-check.
- 
I added the corresponding test.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

2023-12-14 19:12 UTC, RustanLeino requested changes
Looks good, except for the unused declared of `Cutoff`.

2023-12-14 19:12 UTC, RustanLeino commented on Source/DafnyCore/Verifier/BoogieGenerator.Functions.cs
> +  private int Cutoff = 0;
It seems this field is not used.

2023-12-14 20:07 UTC, RustanLeino submitted a review, later dismissed

2024-04-01 17:06 UTC, RustanLeino approved these changes
It seems issue 4823 was fixed between Dafny 4.4 and 4.5.

2024-04-01 20:21 UTC, merged

2024-04-01 21:42 UTC, MikaelMayer commented
Indeed! The fix itself I had originally published got ousted in the merge commit, but at least this PR adds a test.