Implement `:resource_limit` attribute
dafny-lang/dafny pull request #4975
Opened 2024-01-11 19:43 UTC by atomb

### Description

This is an alternative to `:rlimit` that doesn't multiply by 1000 before sending the value to Z3. With the addition of this new attribute, `:rlimit` is deprecated.

The `--resource-limit` flag now passes through the value unchanged, without a multiplication. This flag is currently not used widely, so the impact of this breaking change is minimal.

TODO: include feature description

### How has this been tested?
The integration tests have been updated to use `:resource_limit` wherever they used `:rlimit` previously.

TODO: update the LSP tests and the standard libraries.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

2024-01-15 13:03 UTC, keyboardDrummer commented on Source/DafnyCore/DafnyOptions.cs
> +    public static bool TryParseResourceCount(string value, out uint number) {
Could you rename the parameter `number` to `result` ?

2024-01-16 17:43 UTC, atomb commented on Source/DafnyCore/DafnyOptions.cs
> +      if (value.EndsWith("G")) {
Oh, that might be nice. Thanks for pointing it out!

2024-01-16 23:35 UTC, robin-aws requested changes
Definitely in favor of this cleanup ASAP.

> This flag is currently not used widely, so the impact of this breaking change is minimal.

What also makes me okay with this is that it's a hard breakage: if someone upgrades without being aware of it their verification will likely fail because their limit is suddenly 1/1000th what it was. And if it doesn't then yay, they are better protected against brittleness! :)

2024-01-16 23:35 UTC, robin-aws commented on docs/dev/news/4975.fix
> +The `{:rlimit N}` attribute, which multiplied `N` by 1000 before sending it to Z3, is deprecated in favor of the `{:resource_limit N}` attribute, which can accept string arguments with exponential no
I'd also mention the change in behavior of `--resource-limit`

2024-01-16 23:35 UTC, robin-aws commented on Source/DafnyCore/Options/BoogieOptionBag.cs
> +    false,
What parameter is this? Consider using a named argument or a comment.

2024-01-16 23:35 UTC, robin-aws commented on Source/DafnyCore/Verifier/BoogieGenerator.ExpressionTranslator.cs
> +          // Do this after the above multiplication because :resource_limit should not be multiplied.
We should probably just reject using both attributes at once. At a minimum that check would be here, but perhaps there's a cleaner spot in resolution to catch it earlier?

2024-01-16 23:35 UTC, robin-aws commented on docs/DafnyRef/Attributes.md
>  If using [`{:vcs_split_on_every_assert}`](#sec-vcs_split_on_every_assert) as well, the limit will be set for each assertion.
Hey while you're adding attribute aliases, how about `{:isolate_assertions}`? ;)

(Not literally in this PR of course)

2024-01-17 18:18 UTC, atomb commented
> > This flag is currently not used widely, so the impact of this breaking change is minimal.
> 
> What also makes me okay with this is that it's a hard breakage: if someone upgrades without being aware of it their verification will likely fail because their limit is suddenly 1/1000th what it was. And if it doesn't then yay, they are better protected against brittleness! :)

I'll update the description (and merge message) to mention that. :)

2024-01-17 23:28 UTC, robin-aws approved these changes

2024-01-19 21:23 UTC, merged