Parameter attributes
dafny-lang/dafny pull request #5036
Opened 2024-02-01 10:04 UTC by keyboardDrummer

Fixes #5032

### Description
Support attributes in parameters

### How has this been tested?
Updated an existing littish test

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

2024-02-01 16:13 UTC, MikaelMayer requested changes
Good nice to have. Could you also update the documentation of attributes to add that attributes are supported on parameters now?

2024-02-01 16:13 UTC, MikaelMayer commented on docs/dev/news/5032.feat
> +Function and method parameters and return types, and datatype constructor arguments, can now have attributes. By default, there are no attributes that Dafny recognises in these positions, but custom
```suggestion
Function and method parameters and return types, and datatype constructor arguments, can now have attributes. By default, there are no attributes that Dafny recognizes in these positions, but custom back-ends can use this feature to get extra information from the source files.
```

2024-02-01 16:13 UTC, MikaelMayer commented on Source/DafnyCore/Dafny.atg
> +  { Attribute<ref attributes> }
Indeed, I validate putting these before the other modifiers like ghost or older. We should do the same and put attributes before function and methods keywords as well, but let's keep it for another time.

2024-02-01 22:48 UTC, MikaelMayer commented
> As far as I see, the documentation doesn't say what types of AST nodes support attributes, so it doesn't seem to make sense to say just for parameters that they support attributes.

Can you look for the following in https://dafny.org/latest/DafnyRef/DafnyRef ?
`Formals(allowGhostKeyword, allowNewKeyword`
I think you might want to add `{ Attribute }` before the `GIdentType`

2024-02-02 20:47 UTC, MikaelMayer approved these changes

2024-02-02 22:16 UTC, merged

2024-02-09 00:55 UTC, RustanLeino commented
@keyboardDrummer Sorry to be late to the party, but would you mind adding some tests to `dafny0/AttributeChecks.dfy`. The tests in that file try to make sure that all processing that needs to happen with attributes (like type checking, making sure type characteristics are used properly, etc.) happen.