Warn when using non doo file as a library
dafny-lang/dafny pull request #5313
Opened 2024-04-10 09:57 UTC by keyboardDrummer

### Changes
- Warn when passing non-doo files to --library
- Lots of code was made asynchronous. These locations are performing IO, so it's good that they're async now.

### How has this been tested?
- Updated existing CLI tests

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

2024-04-10 14:04 UTC, robin-aws requested changes

2024-04-10 14:04 UTC, robin-aws commented on Source/DafnyCore/Pipeline/Compilation.cs
> +        $"Use a .doo file to enable Dafny to check that compatible options were used");
```suggestion
```suggestion
        $"The file '{Options.GetPrintPath(unverifiedLibrary)}' was passed to --library. " +
        $"Verification for that file might have used options incompatible with the current ones, or might have been skipped entirely. " +
        $"Use a .doo file to enable Dafny to check that compatible options were used.");
```
```

2024-04-10 14:57 UTC, keyboardDrummer commented on Source/DafnyCore/Pipeline/Compilation.cs
> +      if (file != null) {
Oof, I don't recall why this was needed. Well, fastest way to remember is to remove it again ^,^

2024-04-10 15:38 UTC, keyboardDrummer commented on Source/DafnyCore/Pipeline/Compilation.cs
> +      if (file != null) {
Without it, the tests fail:

```
  Failed stdlibs/StandardLibraries_Errors.dfy [52 s]
  Error Message:
   System.AggregateException : One or more errors occurred. (Command returned non-zero exit code (1): DiffCommand TestFiles/LitTests/LitTest/stdlibs/StandardLibraries_Errors.dfy.expect /home/runner/work/dafny/dafny/dafny/Source/IntegrationTests/bin/Debug/net6.0/TestFiles/LitTests/LitTest/stdlibs/Output/StandardLibraries_Errors.dfy.tmp
Output:
AssertEqualWithDiff() Failure
Diff (changing expected into actual):
 
 Dafny program verifier finished with 1 verified, 0 errors
 
 Dafny program verifier finished with 1 verified, 0 errors
 StandardLibraries_Errors.dfy(20,20): Error: module Std does not exist (position 0 in path Std.Wrappers)
 1 resolution/type errors detected in StandardLibraries_Errors.dfy
 CLI: Error: cannot load DafnyStandardLibraries-notarget.doo: --unicode-char is set locally to False, but the library was built with True
 CLI: Error: cannot load DafnyStandardLibraries.doo: --unicode-char is set locally to False, but the library was built with True
+Encountered internal compilation exception: Object reference not set to an instance of an object.
 Please use the '--check' and/or '--print' option as doo files cannot be formatted in place.
 Please use the '--check' and/or '--print' option as doo files cannot be formatted in place.
```

2024-04-10 23:10 UTC, robin-aws commented on Source/DafnyCore/Pipeline/Compilation.cs
> +      if (file != null) {
Ah that's fair, if the file is missing it should fail more loudly. I forgot that `CreateAndValidate` only returns null if the file wasn't valid.

2024-04-10 23:11 UTC, robin-aws submitted a review, later dismissed

2024-04-11 14:08 UTC, MikaelMayer approved these changes

2024-04-11 14:56 UTC, merged