Try building with .NET 8.0
dafny-lang/dafny pull request #5322
Opened 2024-04-15 16:43 UTC by atomb

### Description

### How has this been tested?

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

2024-09-16 20:53 UTC, tchajed commented
I think it would be good to revisit this. Homebrew has deprecated the Dafny formula because it depends on dotnet 6 which is no longer supported upstream.

2024-09-17 09:12 UTC, keyboardDrummer commented
> I think it would be good to revisit this. Homebrew has deprecated the Dafny formula because it depends on dotnet 6 which is no longer supported upstream.

Agreed. Would be good for Dafny development itself as well.

2024-11-06 09:59 UTC, keyboardDrummer commented
Fuel.legacy.dfy test becomes non-deterministic with this change. It flips between:
```
 Fuel.legacy.dfy(335,26): Error: function precondition could not be proved
 Fuel.legacy.dfy(324,21): Related location
-Fuel.legacy.dfy(313,41): Related location
+Fuel.legacy.dfy(314,46): Related location
```

Both error messages are valid, since they point to two different failing cases of a match.

2025-01-07 13:29 UTC, keyboardDrummer commented
Non-determinism issue has been resolved.

2025-01-07 16:30 UTC, robin-aws requested changes

2025-01-07 16:30 UTC, robin-aws commented on .github/workflows/doc-tests.yml
> +        dotnet-version: 8.0.x
Okay now we really are installing the same version of .NET twice in several workflows, and my comments from an earlier PR to remove the duplication actually apply now :)

2025-01-07 16:30 UTC, robin-aws commented on Source/AutoExtern.Test/AutoExtern.Test.csproj
> +    <TargetFramework>net8.0</TargetFramework>
Could this be moved to `Directory.Build.props` so it only appears once?

2025-01-07 16:30 UTC, robin-aws commented on Source/DafnyServer/SuperLegacySymbolTable.cs
> +      var allExprDotNames = leftSide.OfType<ExprDotName>();
Why did this change?

2025-01-07 16:30 UTC, robin-aws commented on Source/IntegrationTests/TestFiles/LitTests/LitTest/dafny0/Fuel.dfy.expect
How did `Fuel.legacy.dfy.expect` ever work before?

2025-01-07 16:30 UTC, robin-aws commented on Source/DafnyCore/Backends/CSharp/CsharpCodeGenerator.cs
> +      wr.WriteLine("// but the 'dotnet' tool in net8.0 should pick those up automatically.");
```suggestion
      wr.WriteLine("// but the 'dotnet' tool in .NET should pick those up automatically.");
```

Just to avoid some diffs the next time we upgrade.

2025-01-07 16:36 UTC, keyboardDrummer commented on Source/IntegrationTests/TestFiles/LitTests/LitTest/dafny0/Fuel.dfy.expect
I think it relied on the undefined but deterministic ordering of something, like enumerating over a dictionary. I'm guessing there was a performance improvement that made this undefined ordering also non-deterministic, which caused the test to become unstable until I added an explicit ordering.

2025-01-07 16:39 UTC, keyboardDrummer commented on Source/DafnyServer/SuperLegacySymbolTable.cs
> +      var allExprDotNames = leftSide.OfType<ExprDotName>();
@atomb made this change. Rider confirms it's a noop:

<img width="905" alt="image" src="https://github.com/user-attachments/assets/69911a0a-861b-49c2-ada2-36b8e8c0a721" />

Same for the other one I imagine.

2025-01-07 17:31 UTC, robin-aws commented on Source/DafnyServer/SuperLegacySymbolTable.cs
> +      var allExprDotNames = leftSide.OfType<ExprDotName>();
Ah got it, definitely not obvious without context

2025-01-08 17:24 UTC, robin-aws approved these changes
Excelsior!

2025-01-08 17:24 UTC, merged