Feat: Add --rust-module-name to specify a module name
dafny-lang/dafny pull request #5747
Opened 2024-09-04 22:00 UTC by MikaelMayer

Fixes partially #5641

This PR adds `--rust-module-name` so that all absolute paths from crate insert the given module name after "crate" if the option is provided.

### Description
I could have made it a boolean option since it should match the name of the generated file, but by consistency with other backends, I made it so that the option accepts any string. Let me know if you think a boolean would be better.

### How has this been tested?
- A test verifies that in the generated source code, the provided module name is correctly inserted.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

2024-09-05 16:59 UTC, MikaelMayer commented on Source/DafnyCore/Backends/Rust/RustCodeGenerator.cs
> +      var rootType = Options.Get(RustBackend.RustModuleNameOption) is var opt && opt != "" ?
```suggestion
      var rootType = Options.Get(RustBackend.RustModuleNameOption) is {} opt && opt != "" ?
```

2024-09-12 22:22 UTC, robin-aws requested changes
Implementation LGTM, but would love a test case to verify what this unlocks.

2024-09-12 22:22 UTC, robin-aws commented on Source/DafnyCore/Backends/Rust/RustBackend.cs
> +    @"This Option is used to specify the Rust Module Name for the currently translated code, i.e. what goes between crate:: ...  ::module_name".TrimStart()) {
```suggestion
    @"The enclosing Rust module name for the currently translated code, i.e. what goes between crate:: ...  ::module_name".TrimStart()) {
```

2024-09-12 22:22 UTC, robin-aws commented on Source/DafnyCore/Backends/Rust/Dafny-compiler-rust.dfy
> +  datatype CharType = UTF16 | Unicode
nit: "Unicode" is too vague to be much help, consider UTF32 instead

2024-09-12 22:22 UTC, robin-aws commented on Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/rust/custommodule.dfy
Would it be too much to ask for a test case of a manually-written Rust crate, with manually-written Rust code and a Cargo.toml, where you use `dafny translate` to add additional code under a given `--rust-module-name`, and use `cargo test` to verify that all works?

That's the killer application of this option by itself: not forcing the output of Dafny to be the top level namespace, and enabling incremental adoption of Dafny into an existing Rust project!

2024-09-13 15:24 UTC, MikaelMayer commented on Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/rust/custommodule.dfy
Test written. I removed the other one since it was obsolete

2024-09-16 16:05 UTC, robin-aws commented on Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/rust/translate-additional/more_dafny.dfy
Love it!

2024-09-16 16:05 UTC, robin-aws approved these changes

2024-09-16 17:03 UTC, merged