Migrate to .NET Core v2
dafny-lang/dafny pull request #794
Opened 2020-08-13 21:15 UTC by keyboardDrummer

2020-09-21 20:52 UTC, RustanLeino commented
These are two useful big changes, moving to .NET Core and incorporating Boogie as a git submodule. Thank you for your initiative and contributions!

I've tried to merge this with master and I'm having two problems.

One problem is building the parser and scanner, which uses the parser generator Coco/R (found in the `third_party` folder). Until recently, any change to `Dafny.atg` to had be accompanied with a matching change in `Parser.cs` and `Scanner.cs`, which were produced by manually starting Coco. This was changed in PR https://github.com/dafny-lang/dafny/pull/861, which adds Coco as a pre-build event. There are three differences in using this pre-build event with the current PR:

* The working directory (the output directory) of pre-build events is one level deeper, so there needs to be an additional `../` in the three paths in the pre-build event.
* The pre-build event seems to run _after_ the build system has determined which files to include in the build. So, if you manually delete `Parser.cs` and `Scanner.cs` and let the pre-build event rebuild these, then the compiler doesn't yet know about these file, so it generates some errors. If you build again, then this seems to work (but is probably using the prior version of `Parser.cs` and `Scanner.cs`). I don't know how to move this pre-build event earlier.
* When building using `msbuild Dafny.sln`, the build system automatically figures out that `Coco.exe` is a .NET executable, so it prefixes it with `mono` for platforms that need it. This is not happening with `dotnet build Dafny.sln`. One remedy would be to manually add `"mono"` to the pre-build event, but I suspect that would make the build not work on Windows.

The other problem I'm having is that `DafnyDriver` and `DafnyServer` output DLLs, not EXEs. As far as I can tell, the `.csproj` file specifies an `Exe`, but the build still throws in `/target:library` when calling `csc`, and thus you get `Dafny.dll` instead of `Dafny.exe`.

Any ideas of how to solve these problems?

2020-09-21 20:55 UTC, RustanLeino commented
Oh, one more thing. The PR includes the `Test/dafny0/RuntimeTypeTests0` folder, but I think this is an error. This directory is generated when running the `RuntimeTypeTests0.dfy`, so it should be ignored, not checked into the repository.

2020-09-21 22:05 UTC, keyboardDrummer commented
> The working directory (the output directory) of pre-build events is one level deeper, so there needs to be an additional ../ in the three paths in the pre-build event.

Should be solved.

> The pre-build event seems to run after the build system has determined which files to include in the build. So, if you manually delete Parser.cs and Scanner.cs and let the pre-build event rebuild these, then the compiler doesn't yet know about these file, so it generates some errors. If you build again, then this seems to work (but is probably using the prior version of Parser.cs and Scanner.cs). I don't know how to move this pre-build event earlier.

Solved using a different method for specifying a prebuild target.

> When building using msbuild Dafny.sln, the build system automatically figures out that Coco.exe is a .NET executable, so it prefixes it with mono for platforms that need it. This is not happening with dotnet build Dafny.sln. One remedy would be to manually add "mono" to the pre-build event, but I suspect that would make the build not work on Windows.

Solved by using `dotnet tool run` instead of Coco.exe so it's platform independent. This is similar to what Boogie already does [here](https://github.com/boogie-org/boogie/blob/master/Source/Core/Makefile#L12)

> The other problem I'm having is that DafnyDriver and DafnyServer output DLLs, not EXEs. As far as I can tell, the .csproj file specifies an Exe, but the build still throws in /target:library when calling csc, and thus you get Dafny.dll instead of Dafny.exe

On windows those two projects generate .exe files for me. How can I reproduce this problem?

2020-09-21 22:10 UTC, davidcok commented
Remy - I first had the pre-build event build the parser, but then added the parser build into msbuild. So the msbuild should always run Coco and then the compile. Is this not the case? In any case, that is what the dotnet build needs to do.

- David

> On Sep 21, 2020, at 6:05 PM, Remy Willems <notifications@github.com> wrote:
> 
> 
> The working directory (the output directory) of pre-build events is one level deeper, so there needs to be an additional ../ in the three paths in the pre-build event.
> 
> Should be solved.
> 
> The pre-build event seems to run after the build system has determined which files to include in the build. So, if you manually delete Parser.cs and Scanner.cs and let the pre-build event rebuild these, then the compiler doesn't yet know about these file, so it generates some errors. If you build again, then this seems to work (but is probably using the prior version of Parser.cs and Scanner.cs). I don't know how to move this pre-build event earlier.
> 
> Solved using a different method for specifying a prebuild target.
> 
> When building using msbuild Dafny.sln, the build system automatically figures out that Coco.exe is a .NET executable, so it prefixes it with mono for platforms that need it. This is not happening with dotnet build Dafny.sln. One remedy would be to manually add "mono" to the pre-build event, but I suspect that would make the build not work on Windows.
> 
> Solved by using dotnet tool run instead of Coco.exe so it's platform independent. This is similar to what Boogie already does here <https://github.com/boogie-org/boogie/blob/master/Source/Core/Makefile#L12>
> The other problem I'm having is that DafnyDriver and DafnyServer output DLLs, not EXEs. As far as I can tell, the .csproj file specifies an Exe, but the build still throws in /target:library when calling csc, and thus you get Dafny.dll instead of Dafny.exe
> 
> On windows those two projects generate .exe files for me. How can I reproduce this problem?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub <https://github.com/dafny-lang/dafny/pull/794#issuecomment-696403164>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ABITDQATFFELAHPXSXWHHIDSG7E2DANCNFSM4P63LDRQ>.
>

2020-09-21 22:12 UTC, keyboardDrummer commented on .github/workflows/msbuild.yml
>      - name: Build Dafny Parser
I think we can remove this since the dotnet build below here will also run Coco

2020-09-24 01:02 UTC, RustanLeino commented
For the record, for anyone else going from an earlier commit of Dafny to this PR, here what I did that worked for me. Before you build (either inside an IDE like Rider or from the command-line with `msbuild Dafny.sln`), do

    git submodule update --init

from the root Dafny directory. This pulls in the Boogie submodule into the $DAFNY/Source/boogie folder. Once you've done this, you can start the Dafny build as usual.

(If for some reason you have to revert to a previous commit of Dafny, you'll need to run `msbuild Dafny.sln`, then manually delete the `bin` and `obj` folders below $DAFNY/Source, then run `nuget restore Dafny.sln`, and finally run `msbuild Dafny.sln` again.)

The new Dafny does not build `Dafny.exe` (or `DafnyServer.exe`), at least not on a Mac. Instead, it builds `Dafny.dll` (and `DafnyServer.dll`). That's apparently how .NET Core does it. When you previously would have run `mono Dafny.exe`, you will now instead run `dotnet Dafny.dll`. I adjusted the `dafny` script in the Binaries folder to do this.

@fabianhauser When we merge this PR and eventually make a Dafny binary release from it, then the VS Code plug-in will probably need to be changed as mentioned in my previous paragraph.

2020-09-24 01:04 UTC, RustanLeino requested changes
Things now work for me (on a Mac) and look good, except that the Dafny version number is missing when I run Dafny from the command line. How did it disappear?

2020-09-24 13:41 UTC, fabianhauser commented
@RustanLeino To generate a deliverable self contained `.exe` you have to use `dotnet publish` with .NET Core (Also [dotnet deploying documentation: produce an executable](hhttps://docs.microsoft.com/en-us/dotnet/core/deploying/#produce-an-executable))

2020-09-24 13:45 UTC, davidcok commented
I installed dotnet on my Mac and pulled this PR into a new local clone of Dafny. However, I only get problems when trying to build. I note that the instructions for building from source on Linux & Mac on https://github.com/dafny-lang/dafny/wiki/INSTALL have not been updated for the new dotnet configuration. I expect I'm missing some other installation requirements, but it is not clear what they are.

2020-09-24 17:22 UTC, keyboardDrummer commented on Binaries/dafny-server
> +    DAFNYSERVER_EXE_NAME="Dafny.dll"
Missing Server

2020-09-24 17:22 UTC, keyboardDrummer commented on Binaries/dafny-server
> +    DAFNYSERVER_EXE_NAME="Dafny.exe"
Missing Server

2020-09-24 17:22 UTC, keyboardDrummer commented on Source/Dafny/Makefile
> +	dotnet tool run Dafny.atg -namespace Microsoft.Dafny -frames $(FRAME_DIR)
Missing coco

2020-09-24 17:22 UTC, keyboardDrummer commented on Source/Dafny/Makefile.Linux
> +	dotnet tool run Dafny.atg -namespace Microsoft.Dafny -frames $(FRAME_DIR)
Missing coco

2020-09-24 17:22 UTC, keyboardDrummer commented on Source/Dafny/Makefile.Linux
> +	dotnet tool run Dafny.atg -namespace Microsoft.Dafny -frames $(FRAME_DIR)
Missing coco

2020-09-24 17:22 UTC, keyboardDrummer commented on Source/DafnyDriver/Properties/launchSettings.json
> +{
File should not be here

2020-09-24 17:36 UTC, keyboardDrummer commented on Source/Dafny/DafnyPipeline.csproj
> -    <None Include="Dafny.atg" />
Does this need to be included on the right to trigger recompilation when it's changed?

2020-09-24 17:57 UTC, keyboardDrummer commented
> Things now work for me (on a Mac) and look good, except that the Dafny version number is missing when I run Dafny from the command line. How did it disappear?

That was a bug. It's resolved now.

2020-09-24 18:07 UTC, keyboardDrummer commented
> I installed dotnet on my Mac and pulled this PR into a new local clone of Dafny. However, I only get problems when trying to build. I note that the instructions for building from source on Linux & Mac at https://github.com/dafny-lang/dafny/blob/master/INSTALL.md and https://github.com/dafny-lang/dafny/wiki/INSTALL have not been updated for the new dotnet configuration. I expect I'm missing some other installation requirements, but it is not clear what they are.

I've updated the `INSTALL.md` file. Could you check if the updated instructions work for you?

2020-09-24 18:13 UTC, keyboardDrummer commented
> @RustanLeino To generate a deliverable self contained `.exe` you have to use `dotnet publish` with .NET Core (Also see [dotnet deploying documentation: produce an executable](https://docs.microsoft.com/en-us/dotnet/core/deploying/#produce-an-executable))

@fabianhauser, I'm guessing that for the VSCode extension it will be easiest to run Dafny using `dotnet Dafny.dll`, as is mentioned [here](https://docs.microsoft.com/en-us/dotnet/core/deploying/#produce-a-cross-platform-binary), instead of using platform specific executables, right?

2020-09-24 18:43 UTC, davidcok commented
The build (as in dotnet build Dafny.sln) does not build DafnyRuntime.jar,  causing tests that exercise the compile-to-java to fail. KRML and I suggest that the build create the DafnyRuntime.jar if java is installed and issue a warning message if java is not installed.

2020-09-24 18:51 UTC, davidcok commented
INSTALL.md for Mac: step 5 mentions mono. Perhaps this should be dotnet?

Step 7 mentions installing java. Suggest including that optional step before the build of Dafny, so that the dafny build can build the DafnyRuntime.jar if desired. Should also say that java should be at least version 8.

2020-09-24 19:02 UTC, keyboardDrummer commented
> The build (as in dotnet build Dafny.sln) does not build DafnyRuntime.jar, causing tests that exercise the compile-to-java to fail. KRML and I suggest that the build create the DafnyRuntime.jar if java is installed and issue a warning message if java is not installed.

I'm not sure what you mean. Is there a test that should be added? All the tests were passing right?

> Step 7 mentions installing java. Suggest including that optional step before the build of Dafny, so that the dafny build can build the DafnyRuntime.jar if desired. Should also say that java should be at least version 8.

Maybe something for a follow-up PR? I've tried only to change the things related to .NET Core.

2020-09-24 19:30 UTC, davidcok commented
The build creates the DafnyRuntime for cs, but not for java. Consequently, lit tests will fail out of the box. It is preferable if Dafny.sln builds DafnyRuntime.jar, so that it is guaranteed up to date. This could be put off to a subsequent PR if you like. Otherwise this PR is sufficiently ready to merge.

2020-09-24 22:54 UTC, keyboardDrummer commented
> The build creates the DafnyRuntime for cs, but not for java. Consequently, lit tests will fail out of the box. It is preferable if Dafny.sln builds DafnyRuntime.jar, so that it is guaranteed up to date.

This is also the existing behavior right? The .NET Framework build does not trigger building the Dafny runtime for Java from what I see. I'd prefer to keep changing that out of scope for this PR, since the PR is big enough.

2020-09-24 23:23 UTC, RustanLeino commented
> > The build creates the DafnyRuntime for cs, but not for java. Consequently, lit tests will fail out of the box. It is preferable if Dafny.sln builds DafnyRuntime.jar, so that it is guaranteed up to date.
> 
> This is also the existing behavior right? The .NET Framework build does not trigger building the Dafny runtime for Java from what I see. I'd prefer to keep changing that out of scope for this PR, since the PR is big enough.

Correct and I agree.

2020-09-24 23:23 UTC, RustanLeino approved these changes

2020-09-24 23:27 UTC, merged