#749: documentation: added discussion of Unicode support
dafny-lang/dafny pull request #819
Opened 2020-08-22 15:39 UTC by davidcok

Fixes #749. Added 818 because unicode is not yet supported.

2020-09-02 18:00 UTC, acioc commented on docs/_includes/Grammar.md
> +Characters that can appear in a string constant. See the [discussion on unicode support](#sec-unicode).
```suggestion
Characters that can appear in a string constant.
See the [discussion on unicode support](#sec-unicode).
```

2020-09-02 18:00 UTC, acioc commented on docs/_includes/Grammar.md
> +Characters that can appear in a verbatim string. See the [discussion on unicode support](#sec-unicode).
```suggestion
Characters that can appear in a verbatim string.
See the [discussion on unicode support](#sec-unicode).
```

2020-09-02 18:00 UTC, acioc commented on docs/_includes/Grammar.md
> +end-of-comment delimiters, the contents of a comment are not interpreted.
```suggestion
Other than looking for  end-of-comment delimiters,
the contents of a comment are not interpreted.
```

2020-09-02 18:01 UTC, acioc commented on docs/_includes/Grammar.md
> +Comments may contain any unicode character, but see the [discussion on unicode support](#sec-unicode).
```suggestion
Comments may contain any unicode character, but see the [discussion on unicode support](#sec-unicode) for more information.
```

2020-09-02 18:01 UTC, acioc commented on docs/_includes/Grammar.md
> +or a reserved word. Also, `ident` tokens that begin with an `_` are not permitted as user identifiers.
```suggestion
or a reserved word.
Also, `ident` tokens that begin with an `_` are not permitted as user identifiers.
```

2020-09-02 18:04 UTC, acioc commented on docs/_includes/Grammar.md
>  constant has type `char`.
```suggestion
A character constant is enclosed by "'" and includes
either a character from the ``charChar`` set or an escaped character.
Note that although Unicode letters are not allowed in Dafny identifiers,
Dafny does support [Unicode in its character, string, and verbatim strings constants and in its comments](#sec-unicode).
A character constant has type `char`.
```

2020-09-07 14:58 UTC, davidcok commented on docs/DafnyReferenceManual/DafnyRef.md
> -
Grammar.md was included twice, by cut&paste accident. Removing one instance.

2020-09-11 23:56 UTC, RustanLeino commented on docs/_includes/Grammar.md
> +Dafny source code files are readable text encoded as UTF-8 Unicode (because this is what the CoCo-generated scanner and parser read).
`Coco` is written with only one capital C

2020-10-06 20:56 UTC, RustanLeino requested changes

2020-10-06 20:56 UTC, RustanLeino commented on docs/_includes/Grammar.md
> +(because this is what the CoCo-generated scanner and parser read).
```suggestion
(because this is what the Coco/R-generated scanner and parser read). 
```

2020-10-06 20:56 UTC, RustanLeino commented on docs/_includes/Grammar.md
> +However, a current limitation is that the Coco tool used by Dafny is not up to date,
```suggestion
However, a current limitation is that the Coco/R tool used by Dafny is not up to date,
```

2020-10-06 20:56 UTC, RustanLeino approved these changes

2020-10-06 21:18 UTC, RustanLeino commented on docs/DafnyReferenceManual/DafnyRef.md
> +
```suggestion
```

I accidentally re-introduced these lines in the merge.

2020-10-06 21:29 UTC, RustanLeino approved these changes

2020-10-06 21:31 UTC, merged